### ISSUE TITLE
Request9RxProgressKtTest is failing in 'rx' branch

### ISSUE THREAD

**Issue by vidhithakrar** [kotlin-hands-on/intro-coroutines#20]
In the `rx` branch, `Request9RxProgressKtTest` is failing due to `AssertionError`.

It seems the test is failing due to the improvement made in `loadContributorsReactiveProgress` function by using `Observable.scan()` function instead of `Observable.map()` as highlighted below:

```
return repoUsers
        .scan(listOf()) { allUsers, users ->
            (allUsers + users).aggregate()
        }
```

The problem here is `scan()` function emits the `initialValue` while subscribing, in this case, empty list and hence the test assertion is failing.

There are two ways to solve this:
 1) Go back t use `map()` instead of `scan()` 
2) Apply `filter()` to filter out the empty list after `scan()`

I think the second one is kind of confusing, so can go ahead with first. Thoughts?

**Comment by vidhithakrar** [comment]
Or I can think of two more approaches:

3. Since it is the behaviour of `scan` operator in RxJava where it is emitting the `initialValue`, we can skip that first emitted empty list by using `skip(1)` operator
4. Use `scan` without `initialValue` but in that case, aggregation need to happen after `scan` as the first emitted item is not going to be passed as it is without the lambda function call.

**Comment by svtk** [comment]
Thank you for pointing it out! Since the solution is otherwise correct, I've simply changed the test.
