### ISSUE TITLE
Use CountDownLatch instead of AtomicInteger

### ISSUE THREAD

**Issue by 1gravity** [kotlin-hands-on/intro-coroutines#22]
To fix the callback solution I suggest to use a CountDownLatch instead of an AtomicInteger based solution. It won't save LOC but allows for a more decoupled solution (updating the results isn't part of the backend call code):

```
val countDownLatch = CountDownLatch(repos.size)
for (repo in repos) {
    service.getRepoContributorsCall(req.org, repo.name).onResponse { responseUsers ->
        // more code here
        countDownLatch.countDown()
    }
}

countDownLatch.await()
updateResults(allUsers.aggregate())
```

**Comment by svtk** [comment]
That's a good improvement, thank you! I'll update the solution.
