### ISSUE TITLE
ConcurrentTest fails with 'This job has not completed yet'

### ISSUE THREAD

**Issue by lotharschulz** [kotlin-hands-on/intro-coroutines#4]
[Request5ConcurrentKtTest.kt](https://github.com/kotlin-hands-on/intro-coroutines/blob/master/test/tasks/Request5ConcurrentKtTest.kt) fails for me with: 
```
java.lang.IllegalStateException: This job has not completed yet
```
Maybe this gets fixed once
  - https://github.com/Kotlin/kotlinx.coroutines/pull/1206 is merged
and
  - https://github.com/Kotlin/kotlinx.coroutines/issues/1204 is fixed and rolled out

kotlin version used: `1.3.41`

**Comment by svtk** [comment]
You're supposed to have this error if you follow step #9 and call `async` with the explicit dispatcher in `Request5ConcurrentKtTest.kt`. Is it your case or it's different?
See "We can try calling launch with the context of Dispatchers.Default in the example above and make sure the test fails: we will get an exception saying that the job has not completed yet." in https://play.kotlinlang.org/hands-on/Introduction%20to%20Coroutines%20and%20Channels/09_Testing.
(I should emphasize that `//TODO: uncomment this assertion` should be done during the last step)
